package day18;

import java.util.Scanner;

public class ExceptionDemo {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        /*
        System.out.println("program started.");
        System.out.println("enter a number..");
        int num = sc.nextInt();
        System.out.println("divinding 100 by num: "+ 100/num);
        System.out.println("program is completed...");
        System.out.println("program terminated.");
         */

         /*int arr[] =new int[5];
        
         System.out.println("enter the position(0-4): ");
         int pos = sc.nextInt();
         System.out.println("enter the value: ");
         int val = sc.nextInt();
         arr[pos] = val;
         System.out.println(arr[pos]);
         */

         /*String s = null;
         System.out.println(s.length()); 
        */
        sc.close();
         }
}
